services:
  contacts-api:
    build:
      context: .
      dockerfile: src/ContactBook.Contacts.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__contactsDb=Host=postgres;Database=ContactBook;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres

  reports-api:
    build:
      context: .
      dockerfile: src/ContactBook.Reports.API/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__reportsDb=Host=postgres;Database=ContactBookReports;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
      #- kafka

  # reports-consumer:
  #   build:
  #     context: .
  #     dockerfile: src/ContactBook.Reports.Consumer/Dockerfile
  #   environment:
  #     - DOTNET_ENVIRONMENT=Development
  #     - ConnectionStrings__contactsDb=Host=postgres;Database=reportsdb;Username=postgres;Password=postgres
  #     - ConnectionStrings__reportsDb=Host=postgres;Database=ContactBookReports;Username=postgres;Password=postgres
  #   depends_on:
  #     - postgres
  #     - kafka

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # - POSTGRES_DB=contactsdb
    ports:
      - "5432:5432"
    volumes:
      - $HOME/pgdata:/var/lib/postgresql/data

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
