<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ContactBook.Reports.Consumer-63705fbf-6d94-4f91-a45e-74b9e9c40971</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContactBook.Contacts.Infrastructure\ContactBook.Contacts.Infrastructure.csproj" />
    <ProjectReference Include="..\ContactBook.Reports.Infrastructure\ContactBook.Reports.Infrastructure.csproj" />
  </ItemGroup>
</Project>
