// <auto-generated />
using System;
using ContactBook.Reports.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactBook.Reports.Infrastructure.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20250801153226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactBook.Reports.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ContactBook.Reports.Domain.Entities.Report", b =>
                {
                    b.OwnsMany("ContactBook.Reports.Domain.Entities.LocationStatistics", "Data", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("ContactCount")
                                .HasColumnType("integer");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PhoneCount")
                                .HasColumnType("integer");

                            b1.HasKey("ReportId", "__synthesizedOrdinal");

                            b1.ToTable("Reports");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
